---
title: "Assignment 1"
date: "Feb 1, 2026"
date-modified: "last-modified"
format: html
execute: 
  freeze: true
editor: visual
---

::: callout-note
## Creating Enlightening and Truthful Data Visualisations Using Survey Data

Creating enlightening and truthful data visualisations requires careful attention to accuracy, transparency, and effective communication. High-quality visualisations not only present data clearly and attractively, but also enable audiences to understand patterns, relationships, and insights quickly and correctly. This assignment emphasises ethical and analytical approaches to visualising survey data.
:::

## Overview

This handout provides the context, task, expectations and grading criteria of Assignment 1. Students must review and understand them before getting started with the take-home exercise.

## Setting the scene

An online questionnaire survey was conducted from March to May 2023 to collect data on factors affecting learning performances of students at the University of Education - Vietnam National University, Hanoi. The questionnaire comprises of 22 questions. They are divided into to groups.

The first group (A) included demographic variables such as gender, course, ethnicity, parents’ qualifications and occupations, family’s economic status, and the motivation behind choosing their current major. The second group (B) comprised questions about the student’s perceptions and assessments of the lecturers and university, addressing their adaptation to the learning environment and university instructional methods, the level of lecturer support, quality of teaching lecturers, adequacy of university facilities, appropriateness of training curriculum, and competition’s level within classrooms and the influence of peers on learning.

The questionnaire was designed on Google Forms and sent to students and alumni. The sample comprised students who were studying or had graduated from the university. A total of 2238 individuals voluntarily participated and responded to the survey. After cleaning the raw survey data, the final data set consists of 2170 responses.

The data set is available for download at [Mendeley Data](https://data.mendeley.com/datasets/23ppcdbmhc/1).

## The Task

For this assignment, you are required to apply appropriate visuall Analytics methods to reveal and communicate key observations derived from the analysis.  The observations should be presented in **at least eight** and **no more than ten** Tableau dahsboads.

The specific tasks of this assignment are:

-   Applying appropriate univariate data visualisation to show the profile of the respondents.

-   Applying appropriate survey data visualisation to reveal responses of the behaviour questions.

-   Apply appropriate bivariate data visualisation to show the factors affecting learning performance.   

## The Designing Tool

The data visualisation must be prepared by using **Tableau Desktop Professional Edition** and published on **Tableau Public**.

## The Write-up

The write-up of the take-home exercise should include but not limited to the followings:

-   A reproducible description of the procedures used to prepare the analytical visualisation.

-   A write-up of no more than **150 words** per each data visualisation, describing and discussing the patterns reveal by each visualisation prepared.


## Grading Criteria

This assignment will be graded by using the following criteria:

- Data wrangling (20 marks): This is an important aspect of visual analytics. You will be assessed on your ability to employ appropriate Tableau functions to import, extract, clean, transform and process data. Besides assessing your ability to use the Tableau functions, this criterion also includes your ability to clean and derive appropriate variables to meet the visual analysis need.

Visual Analysis (30 marks): In this exercise, you are expected to utilise the visual analytics methods and design best practices introduced in class, along with the Tableau methods learned during the in-class exercises, to perform your analysis. You will be assessed on your ability to apply these methods correctly and to provide accurate interpretations and discussions of the analysis results.

- Visual Communication (20 marks): In this section, your ability to effectively communicate visual analysis results through user-friendly visual representations will be assessed. Since this course is focused on visual analysis, it is crucial that you demonstrate proficiency in using appropriate visualization techniques to clearly convey the findings of your analysis.

- Reproducibility (15 marks): This is a key learning outcome of this course. You will be assessed on your ability to thoroughly document the data visualisation design procedures. 

- Bonus (15 marks): Demonstrate your ability to employ methods beyond what you had learned in class to gain insights from the data. The methods used must be visual analytics in nature.

## Submission Instructions

This is an individual assignment. You are required to work on the assignment and prepare submission individually.

Students are required to The specific submission instructions are as follows:

-   Publish the data visualisation report on Tableau Pulic and provide the url on eLearn.  The report must be in Tableau **Story** format.
-   Upload the Tableau Workbook of the assignment submission on eLearn, and
-   upload the MS Word version of the write-up of the assignment on eLearn.  It should include but not limited to the [write-up](https://va4bi-ay2025-26t2-g2.netlify.app/assign/assign1#the-task) requirements above. 

### Submission date

The completed take-home exercise is due on **22th February 2026 (Sunday) by 11:59pm mid-night**.

## Source

Ngoc Le, Diep (2024), “[Dataset about VNU students](https://data.mendeley.com/datasets/23ppcdbmhc/1)”, Mendeley Data, V1, doi: 10.17632/23ppcdbmhc.1
