---
title: "Lesson 8: Visualising and Analysing Network Data"
date: "January 1, 2026"
date-modified: "last-modified"
format: html
editor: visual
---

## Content

-   Introduction to Graph Data Visualisation
    -   Basic principles of network graph
    -   Graph data visualisation in actions
-   Network Graph Data
    -   Network data sets
    -   Graph data format
    -   Graph Database
-   Network Graph Visualisation Tools
-   Designer toolkit
    -   Gephi
-   Programmer toolkit
    -   R packages
-   Graph layouts
    -   Node-and-link layouts
    -   Force-directed layout
    -   Node-only layout
    -   Adjacency matrix
-   Visual Attributes
    -   Key node attributes
    -   Key edge attributes
    -   Bundles, shapes, images, and more
-   Visual Analysis of Network Graphs
    -   Relationships
    -   Hierarchies
    -   Communities
-   Flows
-   Spatial networks

## Lesson Slides and Hands-on Notes

-   [Lesson 9: Visualising and Analysing Network Data]() slides

## Readings

-   [Visual Analysis of Complex Networks for Business Intelligence with Gephi](https://hal.archives-ouvertes.fr/hal-00828795/document)
-   [Graph Drawing](http://en.wikipedia.org/wiki/Graph_drawing)
-   [Graph Analytics - Lesson Learned and Challenges Ahead](https://www.cs.umd.edu/users/ben/papers/Wong2011Graph.pdf)
-   [Learning to Read and Interpret Network Graph Data Visualizations](http://noduslabs.com/cases/learn-read-interpret-network-graphs-data-visualization/)
-   [The Visualization of Networks](http://www.vismaster.eu/news/von/)
-   [ViZster: Visualizing Online Social Networks](http://hci.stanford.edu/jheer/projects/vizster/early_design/)
-   Adam Perer. ["Finding Beautiful Insights in the Chaos of Social Network Visualizations"](http://perer.org/papers/adamPerer-BV_ch10.pdf). In '''Beautiful Visualization'''. O'Reilly Press.
-   [Visual Complexity](http://www.visualcomplexity.com/vc/)

